apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ballista.fullname" . }}-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  hostPath:
    path: {{ .Values.storage.hostPath }}