apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ballista.fullname" . }}-pvc
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}